// <auto-generated />
using System;
using DuurzaamWoningKompas.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DuurzaamWoningKompas.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260706002134_AddLeadSubmissionId")]
    partial class AddLeadSubmissionId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "lead_status", new[] { "new", "contacted", "appointment_scheduled", "quote_created", "won", "lost" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "product_category", new[] { "general", "thuisbatterij", "warmtepomp", "isolatie", "zonnepanelen", "laadpaal", "airconditioning", "energieadvies" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DuurzaamWoningKompas.Api.Domain.ConsentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AdviceConsent")
                        .HasColumnType("boolean");

                    b.Property<string>("ConsentText")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("character varying(1200)");

                    b.Property<string>("ConsentVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<bool>("MatchingConsent")
                        .HasColumnType("boolean");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.ToTable("consent_records", (string)null);
                });

            modelBuilder.Entity("DuurzaamWoningKompas.Api.Domain.EnergyProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ElectricityUsageKwh")
                        .HasColumnType("integer");

                    b.Property<string>("EnergyContractType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int?>("FeedInKwh")
                        .HasColumnType("integer");

                    b.Property<int>("GasUsageM3")
                        .HasColumnType("integer");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SolarPanelCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LeadId")
                        .IsUnique();

                    b.ToTable("energy_profiles", (string)null);
                });

            modelBuilder.Entity("DuurzaamWoningKompas.Api.Domain.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DesiredStartTerm")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("PrimaryGoal")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ProductInterest")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("SubmissionId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email");

                    b.HasIndex("ProductInterest");

                    b.HasIndex("Status");

                    b.HasIndex("SubmissionId")
                        .IsUnique();

                    b.ToTable("leads", (string)null);
                });

            modelBuilder.Entity("DuurzaamWoningKompas.Api.Domain.LeadInterest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.HasIndex("Value");

                    b.ToTable("lead_interests", (string)null);
                });

            modelBuilder.Entity("DuurzaamWoningKompas.Api.Domain.LeadNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.ToTable("lead_notes", (string)null);
                });

            modelBuilder.Entity("DuurzaamWoningKompas.Api.Domain.LeadProperty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuildYearRange")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("HomeType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("SolarPanels")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("LeadId")
                        .IsUnique();

                    b.HasIndex("Postcode");

                    b.ToTable("lead_properties", (string)null);
                });

            modelBuilder.Entity("DuurzaamWoningKompas.Api.Domain.LeadSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Gclid")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("LandingPage")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Referrer")
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.Property<string>("UtmCampaign")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.Property<string>("UtmContent")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("UtmMedium")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("UtmSource")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("UtmTerm")
                        .HasMaxLength(180)
                        .HasColumnType("character varying(180)");

                    b.HasKey("Id");

                    b.HasIndex("LeadId")
                        .IsUnique();

                    b.HasIndex("UtmCampaign");

                    b.HasIndex("UtmSource");

                    b.ToTable("lead_sources", (string)null);
                });

            modelBuilder.Entity("DuurzaamWoningKompas.Api.Domain.LeadStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Note")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.ToTable("lead_status_history", (string)null);
                });

            modelBuilder.Entity("DuurzaamWoningKompas.Api.Domain.ConsentRecord", b =>
                {
                    b.HasOne("DuurzaamWoningKompas.Api.Domain.Lead", null)
                        .WithMany("ConsentRecords")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DuurzaamWoningKompas.Api.Domain.EnergyProfile", b =>
                {
                    b.HasOne("DuurzaamWoningKompas.Api.Domain.Lead", null)
                        .WithOne("EnergyProfile")
                        .HasForeignKey("DuurzaamWoningKompas.Api.Domain.EnergyProfile", "LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DuurzaamWoningKompas.Api.Domain.LeadInterest", b =>
                {
                    b.HasOne("DuurzaamWoningKompas.Api.Domain.Lead", null)
                        .WithMany("Interests")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DuurzaamWoningKompas.Api.Domain.LeadNote", b =>
                {
                    b.HasOne("DuurzaamWoningKompas.Api.Domain.Lead", null)
                        .WithMany("Notes")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DuurzaamWoningKompas.Api.Domain.LeadProperty", b =>
                {
                    b.HasOne("DuurzaamWoningKompas.Api.Domain.Lead", null)
                        .WithOne("Property")
                        .HasForeignKey("DuurzaamWoningKompas.Api.Domain.LeadProperty", "LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DuurzaamWoningKompas.Api.Domain.LeadSource", b =>
                {
                    b.HasOne("DuurzaamWoningKompas.Api.Domain.Lead", null)
                        .WithOne("Source")
                        .HasForeignKey("DuurzaamWoningKompas.Api.Domain.LeadSource", "LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DuurzaamWoningKompas.Api.Domain.LeadStatusHistory", b =>
                {
                    b.HasOne("DuurzaamWoningKompas.Api.Domain.Lead", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DuurzaamWoningKompas.Api.Domain.Lead", b =>
                {
                    b.Navigation("ConsentRecords");

                    b.Navigation("EnergyProfile")
                        .IsRequired();

                    b.Navigation("Interests");

                    b.Navigation("Notes");

                    b.Navigation("Property")
                        .IsRequired();

                    b.Navigation("Source")
                        .IsRequired();

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
